force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Race.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Laps__c.field-meta.xml
<CustomField>
    <fullName>Laps__c</fullName>
    <description>Number of Laps</description>
    <inlineHelpText>Number of Laps</inlineHelpText>
    <label>Laps</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVUS</fullName>
            </value>
            <value>
                <fullName>Circuit de Monaco</fullName>
            </value>
            <value>
                <fullName>Mosport Park</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PostponeRaceBatchTest.cls
@isTest
public class PostponeRaceBatchTest {
    @TestSetup
    static void makeData(){
        List<Race__c> races = new List<Race__c>();
        for (Integer i = 1; i < 5; i++) {
            races.add(new Race__c(
                Name = 'Race_' + i,
                Date__c = Date.newInstance(2021, i, 8),
                Track__c = 'Circuit de Monaco',
                Laps__c = 4
            ));
        }
        insert races;
    }

    @isTest
    static void testBatch() {
        Test.setMock(HttpCalloutMock.class, new MockHttp());

        Test.startTest();
        PostponeRaceBatch batch = new PostponeRaceBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        Race__c[] races = [SELECT Date__c FROM Race__c ORDER BY Date__c];
        System.assertEquals(2, races[0].Date__c.month());
        System.assertEquals(3, races[1].Date__c.month());
        System.assertEquals(4, races[2].Date__c.month());
        System.assertEquals(5, races[3].Date__c.month());
    }
}