force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.).</description>
    <label>Driver</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Drivers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver.</description>
    <inlineHelpText>Age of driver.</inlineHelpText>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the driver</description>
    <inlineHelpText>First Name of the driver</inlineHelpText>
    <label>First Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Concatenation of first name and last name</description>
    <formula>First_Name__c &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the driver.</description>
    <inlineHelpText>Last Name of the driver.</inlineHelpText>
    <label>Last Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Podium_Second__c.field-meta.xml
<CustomField>
    <fullName>Podium_Second__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Podium Second</description>
    <inlineHelpText>Podium Second</inlineHelpText>
    <label>Podium Second</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races (Podium Second)</relationshipLabel>
    <relationshipName>Races1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Podium_Third__c.field-meta.xml
<CustomField>
    <fullName>Podium_Third__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Podium Third</description>
    <inlineHelpText>Podium Third</inlineHelpText>
    <label>Podium Third</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races (Podium Third)</relationshipLabel>
    <relationshipName>Races2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1st place</description>
    <inlineHelpText>1st place</inlineHelpText>
    <label>Winner</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races (Winner)</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <label>Race Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Race Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <inlineHelpText>Participated Race</inlineHelpText>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <description>Grid (initial) position in current Race</description>
    <inlineHelpText>Grid (initial) position in current Race</inlineHelpText>
    <label>Grid</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows if Driver has done the fastest lap during the Race</description>
    <inlineHelpText>Shows if Driver has done the fastest lap during the Race</inlineHelpText>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position in current Race</description>
    <inlineHelpText>Position in current Race</inlineHelpText>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Driver attended the Race</description>
    <inlineHelpText>Driver attended the Race</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormulaOneServicesTest.cls
@isTest
private class FormulaOneServicesTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createDriversAndRacesWithResults(4, 2);
    }

    @isTest
    static void generateKeyTest() {
        SObjectType accountType = Schema.getGlobalDescribe().get('Driver__c');
        Map<String, SObjectField> mfields = accountType.getDescribe().fields.getMap();
        String[] fieldNames = new List<String>{
            'Id', 'First_Name__c', 'Last_Name__c', 'Full_Name__c', 'Age__c'
        };
        
        SObjectField[] fields = new List<SObjectField>();
        for (String fieldName: fieldNames) {
            fields.add(mfields.get(fieldName));
        }
        
        Driver__c driver = Database.query(
            'SELECT ' + String.join(fieldNames, ', ')
            + ' FROM Driver__c LIMIT 1'
        );

        List<Object> testValues = new List<Object>();
        for (SObjectField field: fields) {
            Object value = driver.get(field);
            testValues.add(value);
        }
        String testKey = testValues.toString();

        Test.startTest();
        String key = FormulaOneServices.generateKey(driver, fields, ', ');
        Test.stopTest();

        System.assertEquals(testKey, key, 'Wrong key has been received.');
    }

    @isTest
    static void isHatTrickTest() {
        Race_Result__c hatTrickResult = new Race_Result__c(
            Name = 'Test Result',
            Position__c = 1,
            Grid__c = 1,
            Is_Fastest_Lap__c = true
        );
        Race_Result__c notHatTrickResult = new Race_Result__c(
            Name = 'Test Falsy Result',
            Position__c = 2,
            Grid__c = 1,
            Is_Fastest_Lap__c = false
        );

        Test.startTest();
        Boolean isHatTrick = FormulaOneServices.isHatTrick(hatTrickResult);
        Boolean isNotHatTrick = FormulaOneServices.isHatTrick(notHatTrickResult);
        Test.stopTest();

        System.assertEquals(true, isHatTrick);
        System.assertEquals(false, isNotHatTrick);
    }

    @isTest
    static void createDriverTest() {
        String fname = 'TestFirstname';
        String lname = 'TestLastName';
        Integer age = 33;

        Test.startTest();
        FormulaOneServices.createDriver(fname, lname, age);
        Test.stopTest();

        Driver__c driver = [
            SELECT Id, First_Name__c, Last_Name__c, Age__c 
            FROM Driver__c 
            WHERE First_Name__c=:fname AND Last_Name__c=:lname AND Age__c=:age
        ];

        System.assertEquals(fname, driver.First_Name__c);
        System.assertEquals(lname, driver.Last_Name__c);
        System.assertEquals(age, driver.Age__c);
    }

    @isTest
    static void createDriversTest() {
        String fname = 'TestDriver';
        String lname = 'CreatedFromDTO';
        Integer age = 42;

        DriverDTO[] driversDTO = new List<DriverDTO>();
        for (Integer i = 0; i < 5; i++) {
            driversDTO.add(new DriverDTO(fname, lname, age));
        }

        Test.startTest();
        FormulaOneServices.createDrivers(driversDTO);
        Test.stopTest();

        Driver__c[] drivers = [
            SELECT First_Name__c, Last_Name__c, Age__c
            FROM Driver__c
            WHERE First_Name__c=:fname AND Last_Name__c=:lname AND Age__c=:age
        ];

        System.assertEquals(5, drivers.size());
        for (Driver__c driver: drivers) {
            System.assertEquals(fname, driver.First_Name__c);
            System.assertEquals(lname, driver.Last_Name__c);
            System.assertEquals(age, driver.Age__c);
        }
    }

    @isTest
    static void updateDriverNameTest() {
        String fname = 'UpdatedTestDriverName';
        String lname = 'UpdatedTestDriverLastName';
        Driver__c driver = [SELECT First_Name__c, Last_Name__c FROM Driver__c LIMIT 1];

        Test.startTest();
        Driver__c updatedDriver = FormulaOneServices.updateDriverName(driver.Id, fname, lname);
        Test.stopTest();

        System.assertEquals(driver.Id, updatedDriver.Id);
        System.assertEquals(fname, updatedDriver.First_Name__c);
        System.assertEquals(lname, updatedDriver.Last_Name__c);
    }

    @isTest
    static void updateGrandPrixWinnersTest() {
        Race__c[] races = [
            SELECT Id, (SELECT Racer__r.Id, Position__c 
                        FROM Race_Results__r
                        ORDER BY Position__c
                        LIMIT 3) 
            FROM Race__c 
            LIMIT 2
        ];
        Set<Id> raceIds = new Set<Id>();
        for (Race__c race: races) {
            raceIds.add(race.Id);
        }

        Test.startTest();
        Race__c[] updatedRaces = FormulaOneServices.updateGrandPrixWinners(raceIds);
        Test.stopTest();

        Set<Id> checkedIds = new Set<Id>();
        for (Race__c race: races) {
            for (Race__c updatedRace: updatedRaces) {
                if (race.Id == updatedRace.Id) {
                    checkedIds.add(race.Id);
                    System.assertEquals(race.Race_Results__r.get(0).Racer__c, updatedRace.Winner__c);
                    System.assertEquals(race.Race_Results__r.get(1).Racer__c, updatedRace.Podium_Second__c);
                    System.assertEquals(race.Race_Results__r.get(2).Racer__c, updatedRace.Podium_Third__c);
                }
            }
        }

        System.assert(checkedIds.equals(raceIds));
    }
}