force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.).</description>
    <label>Driver</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Drivers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Concatenation of first name and last name</description>
    <formula>First_Name__c &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <label>Race Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Race Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <inlineHelpText>Participated Race</inlineHelpText>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position in current Race</description>
    <inlineHelpText>Position in current Race</inlineHelpText>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Driver attended the Race</description>
    <inlineHelpText>Driver attended the Race</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RaceResultTriggerHandler.cls
public class RaceResultTriggerHandler {
    List<Race_Result__c> resultsNew;

    public RaceResultTriggerHandler(List<Race_Result__c> resultsNew) {
        this.resultsNew = resultsNew;
    }

    public void checkPositionAndDriverDuplicity() {
        Set<Id> raceIds = new Set<Id>();

        for (Race_Result__c result: this.resultsNew) {
            raceIds.add(result.Grand_Prix__c);
        }

        Race_Result__c[] results = [
            SELECT Grand_Prix__r.Name, Racer__r.Full_Name__c, Position__c
            FROM Race_Result__c 
            WHERE Grand_Prix__c IN :raceIds
        ];

        Map<Id, List<Race_Result__c>> resultsPerRace = new Map<Id, List<Race_Result__c>>();
        for(Id raceId: raceIds) {
            resultsPerRace.put(raceId, new List<Race_Result__c>());
        }

        for (Race_Result__c result: results) {
            resultsPerRace.get(result.Grand_Prix__c).add(result);
        }

        for (Race_Result__c resultNew: this.resultsNew) {
            for (Race_Result__c result: resultsPerRace.get(resultNew.Grand_Prix__c)) {
                if (resultNew.Position__c == result.Position__c && resultNew.Id != result.Id) {
                    String message = 'Duplicaton detected! Position ' + result.Position__c.format() + 
                                    ' in race ' + result.Grand_Prix__r.Name + ' already exists.';
                    resultNew.addError(message);
                }

                if (resultNew.Racer__c == result.Racer__c && resultNew.Id != result.Id) {
                    String message = 'Duplicaton detected! Racer ' + result.Racer__r.Full_Name__c + 
                                    ' in race ' + result.Grand_Prix__r.Name + ' already exists.';
                    resultNew.addError(message);
                }
            }
        }
    }
}