force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.).</description>
    <label>Driver</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Drivers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver.</description>
    <inlineHelpText>Age of driver.</inlineHelpText>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Concatenation of first name and last name</description>
    <formula>First_Name__c &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <label>Race Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Race Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <inlineHelpText>Participated Race</inlineHelpText>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Driver attended the Race</description>
    <inlineHelpText>Driver attended the Race</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormulaOneDAO.cls
public with sharing class FormulaOneDAO {
    public Driver__c getDriver(Id driverId, String[] fields) {
        // return Driver__c object where Id == driverId
        String query = 'SELECT ' + String.join(fields, ', ') + ' FROM Driver__c where Id=:driverId limit 1';
        return Database.query(query);
    }

    public List<Race_Result__c> getRaceResults(Id driverId, String[] raceResultFields) {
        // return List of Race_Result__c objects, where Driver__c equal driverId
        String query = 'SELECT ' + String.join(raceResultFields, ', ') + ' FROM Race_Result__c where Racer__c = :driverId';
        return Database.query(query);
    }

    public Set<String> getDriverCircuits(Id driverId) {
        // return Set of Names for Race__c obects where Driver with Id == driverId participated
        Race_Result__c[] results = [SELECT Grand_Prix__r.Name FROM Race_Result__c WHERE Racer__c = :driverId];
        Set<String> raceNames = new Set<String>();
        
        for (Race_Result__c result: results) {
            raceNames.add(result.Grand_Prix__r.Name);
        }

        return raceNames;
    }

    public Driver__c getYoungestDriverOnRace(Id raceId, String[] fields) {
        // Get youngest drive for specified race
        return Database.query(
            'SELECT ' + String.join(fields, ', ')
            + ' FROM Driver__c'
            + ' WHERE Id IN (SELECT Racer__c FROM Race_Result__c WHERE Grand_Prix__c = :raceId)'
            + ' ORDER BY Age__c'
            + ' LIMIT 1'
        );
    }

    public Map<String, String[]> getAllDriversByCircuit() {
        // return Map where:
        // String - Race__c.Name,
        // List<String> - list of Full Names for drivers that participated the Race
        Map<String, String[]> raceDriversMap = new Map<String, String[]>();
        Race_Result__c[] results = [SELECT Grand_Prix__r.Name, Racer__r.Full_Name__c FROM Race_Result__c];
        
        for (Race_Result__c result: results) {
            if (raceDriversMap.containsKey(result.Grand_Prix__r.Name)) {
                raceDriversMap
                    .get(result.Grand_Prix__r.Name)
                    .add(result.Racer__r.Full_Name__c);
            } else {
                raceDriversMap.put(
                    result.Grand_Prix__r.Name, 
                    new List<String>{result.Racer__r.Full_Name__c}
                );
            }
        }

        return raceDriversMap;
    }
}