force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.).</description>
    <label>Driver</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Drivers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver.</description>
    <inlineHelpText>Age of driver.</inlineHelpText>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the driver</description>
    <inlineHelpText>First Name of the driver</inlineHelpText>
    <label>First Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Concatenation of first name and last name</description>
    <formula>First_Name__c &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the driver.</description>
    <inlineHelpText>Last Name of the driver.</inlineHelpText>
    <label>Last Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Race.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Laps__c.field-meta.xml
<CustomField>
    <fullName>Laps__c</fullName>
    <description>Number of Laps</description>
    <inlineHelpText>Number of Laps</inlineHelpText>
    <label>Laps</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVUS</fullName>
            </value>
            <value>
                <fullName>Circuit de Monaco</fullName>
            </value>
            <value>
                <fullName>Mosport Park</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <label>Race Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Race Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <inlineHelpText>Participated Race</inlineHelpText>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <description>Grid (initial) position in current Race</description>
    <inlineHelpText>Grid (initial) position in current Race</inlineHelpText>
    <label>Grid</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows if Driver has done the fastest lap during the Race</description>
    <inlineHelpText>Shows if Driver has done the fastest lap during the Race</inlineHelpText>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position in current Race</description>
    <inlineHelpText>Position in current Race</inlineHelpText>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Driver attended the Race</description>
    <inlineHelpText>Driver attended the Race</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static void createDriversAndRacesWithResults(Integer numDrivers, Integer numRaces) {
        List<Driver__c> drivers = new List<Driver__c>();
        for (Integer i = 0; i < numDrivers; i++) {
            drivers.add(new Driver__c(
                First_Name__c = 'Test_' + i,
                Last_Name__c = 'Driver',
                Age__c = TestDataFactory.getRandomInteger(18, 50)
            ));
        }
        insert drivers;

        List<Race__c> races = new List<Race__c>();
        for (Integer i = 0; i < numRaces; i++) {
            races.add(new Race__c(
                Name = 'Race_' + i,
                Date__c = TestDataFactory.getRandomDate(),
                Track__c = TestDataFactory.getRandomTrack(),
                Laps__c = TestDataFactory.getRandomInteger(1, 6)
            ));
        }
        insert races;

        List<Race_Result__c> results = new List<Race_Result__c>();
        for (Integer raceIndex = 0; raceIndex < numRaces; raceIndex++) {
            for (Integer driverIndex = 0; driverIndex < numDrivers; driverIndex++) {
                results.add(new Race_Result__c(
                    Name = 'Result ' + drivers.get(driverIndex).Full_Name__c,
                    Grand_Prix__c = races.get(raceIndex).Id,
                    Racer__c = drivers.get(driverIndex).Id,
                    Position__c = driverIndex + 1,
                    Grid__c = driverIndex + 1,
                    Is_Fastest_Lap__c = driverIndex + 1 == 1 ? true : false
                ));
            }
        }
        insert results;
    }

    private static String getRandomTrack() {
        List<String> tracks = new List<String> {
            'AVUS', 'Circuit de Monaco', 'Mosport Park'
        };
        return tracks.get(getRandomInteger(0, tracks.size() - 1));
    }

    private static Date getRandomDate() {
        Date minDate = date.newInstance(2015, 1, 1);
        Date maxDate = date.newInstance(2021, 1, 1);
        Integer rangeSize = minDate.daysBetween(maxDate) + 1;
        Decimal daysToAdd = rangeSize * math.Random();
        Date result = minDate.addDays(daysToAdd.intValue());
        return result;
    }

    private static Integer getRandomInteger(Integer min, Integer max) {
        return Integer.valueOf(Math.random() * (max + 1 - min) + min);
    }
}