force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.).</description>
    <label>Driver</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Drivers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Hat_Tricks__c.field-meta.xml
<CustomField>
    <fullName>Hat_Tricks__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount of won Races finished with the fastest lap and took 1st place.</description>
    <label>Hat Tricks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <label>Race Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Race Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <inlineHelpText>Participated Race</inlineHelpText>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows if Driver has done the fastest lap during the Race</description>
    <inlineHelpText>Shows if Driver has done the fastest lap during the Race</inlineHelpText>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position in current Race</description>
    <inlineHelpText>Position in current Race</inlineHelpText>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Driver attended the Race</description>
    <inlineHelpText>Driver attended the Race</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RaceResultTriggerHandlerTest.cls
@isTest
private class RaceResultTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        TestDataFactory.createDriversAndRacesWithResults(4, 2);
    }

    @isTest
    static void checkPositionAndDriverPostionDuplicityNegativeTest() {
        Race__c race = [
            SELECT Id, Name, (SELECT Position__c FROM Race_Results__r ORDER BY Position__c LIMIT 4)
            FROM Race__c 
            LIMIT 1
        ];

        Race_Result__c[] resultsToInsert = new List<Race_Result__c>();
        for (Integer i = 0; i < 5; i++) {
            resultsToInsert.add(new Race_Result__c(
                Name = 'Test Result ' + i,
                Position__c = 1, // already exists in test setup
                Grand_Prix__c = race.Id
            ));
        }
        
        Race_Result__c[] resultsToUpdate = new List<Race_Result__c>();
        for (Race_Result__c result : race.Race_Results__r) {
            // result with original position 1 will be successfully updated
            if (result.Position__c != 1) {
                result.Position__c = 1;
                resultsToUpdate.add(result);
            }
        }

        Race_Result__c[] resultsToUpsert = new List<Race_Result__c>();
        resultsToUpsert.addAll(resultsToInsert);
        resultsToUpsert.addAll(resultsToUpdate);

        Test.startTest();
        Database.SaveResult[] saveResult = Database.insert(resultsToInsert, false);
        Database.SaveResult[] updateResult = Database.update(resultsToUpdate, false);
        Database.UpsertResult[] upsertResult = Database.upsert(resultsToUpsert, false);
        Test.stopTest();

        String errMessage = 'Duplicaton detected! Position 1 in race ' + race.Name + ' already exists.';
        for (Database.SaveResult dbResult : saveResult) {
            System.assertEquals(false, dbResult.isSuccess());
            System.assert(dbResult.getErrors().size() > 0);
            System.assertEquals(errMessage, dbResult.getErrors()[0].getMessage());
        }

        for (Database.SaveResult dbResult : updateResult) {
            System.assertEquals(false, dbResult.isSuccess());
            System.assert(dbResult.getErrors().size() > 0);
            System.assertEquals(errMessage, dbResult.getErrors()[0].getMessage());
        }

        for (Database.UpsertResult dbResult : upsertResult) {
            System.assertEquals(false, dbResult.isSuccess());
            System.assert(dbResult.getErrors().size() > 0);
            System.assertEquals(errMessage, dbResult.getErrors()[0].getMessage());
        }
    }

    @isTest
    static void updateHatTricksOnRacerTest() {
        Race_Result__c result = [
            SELECT Racer__r.Hat_Tricks__c 
            FROM Race_Result__c
            WHERE Position__c=1 AND Is_Fastest_Lap__c=true
            LIMIT 1
        ];
        Id driverId = result.Racer__r.Id;
        Decimal hatTricks = result.Racer__r.Hat_Tricks__c;

        Test.startTest();
        Database.DeleteResult deleteResult = Database.delete(result, false);
        Test.stopTest();

        System.assert(deleteResult.isSuccess());
        System.assert(deleteResult.getErrors().size() == 0);

        Driver__c driver = [SELECT Hat_Tricks__c FROM Driver__c WHERE Id = :driverId];
        System.assertEquals(hatTricks - 1, driver.Hat_Tricks__c);
    }
}