force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.).</description>
    <label>Driver</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Drivers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver.</description>
    <inlineHelpText>Age of driver.</inlineHelpText>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the driver</description>
    <inlineHelpText>First Name of the driver</inlineHelpText>
    <label>First Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the driver.</description>
    <inlineHelpText>Last Name of the driver.</inlineHelpText>
    <label>Last Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Podium_Second__c.field-meta.xml
<CustomField>
    <fullName>Podium_Second__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Podium Second</description>
    <inlineHelpText>Podium Second</inlineHelpText>
    <label>Podium Second</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races (Podium Second)</relationshipLabel>
    <relationshipName>Races1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Podium_Third__c.field-meta.xml
<CustomField>
    <fullName>Podium_Third__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Podium Third</description>
    <inlineHelpText>Podium Third</inlineHelpText>
    <label>Podium Third</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races (Podium Third)</relationshipLabel>
    <relationshipName>Races2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>1st place</description>
    <inlineHelpText>1st place</inlineHelpText>
    <label>Winner</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Races (Winner)</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <label>Race Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Race Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <inlineHelpText>Participated Race</inlineHelpText>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <description>Grid (initial) position in current Race</description>
    <inlineHelpText>Grid (initial) position in current Race</inlineHelpText>
    <label>Grid</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows if Driver has done the fastest lap during the Race</description>
    <inlineHelpText>Shows if Driver has done the fastest lap during the Race</inlineHelpText>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position in current Race</description>
    <inlineHelpText>Position in current Race</inlineHelpText>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Driver attended the Race</description>
    <inlineHelpText>Driver attended the Race</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormulaOneServices.cls
public with sharing class FormulaOneServices {
    public static String generateKey(SObject record, List<SObjectField> fields, String separator) {
        List<Object> values = new List<Object>();
        for (SObjectField field: fields) {
            Object value = record.get(field);
            values.add(value);
        }

        return values.toString().replace(', ', separator);
    }

    public static Boolean isHatTrick(Race_Result__c raceResult) {
        return raceResult.Position__c == 1 && 
               raceResult.Grid__c == 1 && 
               raceResult.Is_Fastest_Lap__c == true;
    }

    public static void createDriver(String firstName, String lastName, Integer age) {
        // Create insert driver record, based on input parameters
        Driver__c driver = new Driver__c();
        driver.First_Name__c = firstName;
        driver.Last_Name__c = lastName;
        driver.Age__c = age;

        insert driver;
    }

    public static void createDrivers(List<DriverDTO> driversDTO) {
        // Create and insert list of driver records, based on input parameters
        Driver__c[] drivers = new List<Driver__c>();

        for (DriverDTO dto: driversDTO) {
            Driver__c driver = new Driver__c();
            driver.First_Name__c = dto.firstName;
            driver.Last_Name__c = dto.lastName;
            driver.Age__c = dto.age;
            drivers.add(driver);
        }

        insert drivers;
    }

    public static Driver__c updateDriverName(Id driverId, String firstName, String lastName) {
        // Update driver`s name based on input parameters
        Driver__c driver = [SELECT Id, First_Name__c, Last_Name__c FROM Driver__c WHERE Id = :driverId limit 1];
        driver.First_Name__c = firstName;
        driver.Last_Name__c = lastName;

        update driver;
        return driver;
    }

    public static Race__c[] updateGrandPrixWinners(Set<Id> raceIds) {
        // Get Race__c records based by input params and update Winner__c, Podium_Second__c and Podium_Third__c fields 
        // depending on Position__c field of related Race_Result__c objects
        Race_Result__c[] results = [
            SELECT Grand_Prix__r.Winner__c, Grand_Prix__r.Podium_Second__c, Grand_Prix__r.Podium_Third__c, Position__c, Racer__c
            FROM Race_Result__c
            WHERE Grand_Prix__r.Id IN :raceIds AND Position__c IN :new Set<Integer>{1, 2, 3}
        ];
        
        Map<Id, Race__c> races = new Map<Id, Race__c>();
        for (Race_Result__c result: results) {
            if (result.Position__c == 1) {
                result.Grand_Prix__r.Winner__c = result.Racer__c;
            } 
            else if (result.Position__c == 2) {
                result.Grand_Prix__r.Podium_Second__c = result.Racer__c;
            }
            else if (result.Position__c == 3) {
                result.Grand_Prix__r.Podium_Third__c = result.Racer__c;
            }
            races.put(result.Grand_prix__r.Id, result.Grand_prix__r);
        }

        update races.values();
        return races.values();
    }
}