force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <description>Driver&apos;s parameters (First Name, Last Name, etc.).</description>
    <label>Driver</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Drivers ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of driver.</description>
    <inlineHelpText>Age of driver.</inlineHelpText>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the driver</description>
    <inlineHelpText>First Name of the driver</inlineHelpText>
    <label>First Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Concatenation of first name and last name</description>
    <formula>First_Name__c &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name of the driver.</description>
    <inlineHelpText>Last Name of the driver.</inlineHelpText>
    <label>Last Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <description>Object containing description of Race that take place at some time at certain place.</description>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/Race_Result__c.object-meta.xml
<CustomObject>
    <description>Links Race with Driver, which attended the race</description>
    <label>Race Result</label>
    <nameField>
        <label>Race Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Race Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Race_Result__c/fields/Grand_Prix__c.field-meta.xml
<CustomField>
    <fullName>Grand_Prix__c</fullName>
    <description>Participated Race</description>
    <inlineHelpText>Participated Race</inlineHelpText>
    <label>Grand Prix</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Is_Fastest_Lap__c.field-meta.xml
<CustomField>
    <fullName>Is_Fastest_Lap__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Shows if Driver has done the fastest lap during the Race</description>
    <inlineHelpText>Shows if Driver has done the fastest lap during the Race</inlineHelpText>
    <label>Is Fastest Lap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position in current Race</description>
    <inlineHelpText>Position in current Race</inlineHelpText>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Race_Result__c/fields/Racer__c.field-meta.xml
<CustomField>
    <fullName>Racer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Driver attended the Race</description>
    <inlineHelpText>Driver attended the Race</inlineHelpText>
    <label>Racer</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Race Results</relationshipLabel>
    <relationshipName>Race_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormulaOneDAOTest.cls
@isTest
private class FormulaOneDAOTest {
    @testSetup
    static void dataCreation() {
        TestDataFactory.createDriversAndRacesWithResults(4, 2);
    }

    @isTest
    static void getDriverTest() {
        String[] fields = new List<String>{'First_Name__c', 'Last_Name__c', 'Age__c'};
        Driver__c testDriver = Database.query(
            'SELECT ' + String.join(fields, ', ')
            + ' FROM Driver__c'
            + ' LIMIT 1'
        );

        Test.startTest();
        FormulaOneDAO dao = new FormulaOneDAO();
        Driver__c driver = dao.getDriver(testDriver.Id, fields);
        Test.stopTest();

        System.assertEquals(testDriver.First_Name__c, driver.First_Name__c, 'Wrong First_Name__c attribute value.');
        System.assertEquals(testDriver.Last_Name__c, driver.Last_Name__c, 'Wrong Last_Name__c attribute value.');
        System.assertEquals(testDriver.Age__c, driver.Age__c, 'Wrong Age__c attribute value.');
    }

    @isTest
    static void getRaceResultsTest() {
        Driver__c driver = [
            SELECT Id, (SELECT Name, Grand_Prix__c, Position__c, Is_Fastest_Lap__c, Racer__c
                        FROM Race_Results__r)
            FROM Driver__c
            LIMIT 1
        ];

        Test.startTest();
        FormulaOneDAO dao = new FormulaOneDAO();
        // Racer__c field is obligatory, do not remove it. This filed will be queried in subquery above anyway.
        Race_Result__c[] results = dao.getRaceResults(driver.id, new List<String>{
            'Name', 'Grand_Prix__c', 'Position__c', 'Is_Fastest_Lap__c', 'Racer__c'
        });
        Test.stopTest();

        System.assert(results.equals(driver.Race_Results__r), 'Lists of race results are different.');
    }

    @isTest
    static void getDriverCircuitsTest() {
        Driver__c driver = [
            SELECT Id, (SELECT Name, Grand_Prix__r.Name FROM Race_Results__r)
            FROM Driver__c
            LIMIT 1
        ];
        Set<String> testRaceNames = new Set<String>();
        for (Race_Result__c result: driver.Race_Results__r) {
            testRaceNames.add(result.Grand_Prix__r.Name);
        }

        Test.startTest();
        FormulaOneDAO dao = new FormulaOneDAO();
        Set<String> raceNames = dao.getDriverCircuits(driver.Id);
        Test.stopTest();

        System.assert(raceNames.equals(testRaceNames));
    }

    @isTest
    static void getYoungestDriverOnRaceTest() {
        Race__c race = [
            SELECT Id, (SELECT Racer__r.Age__c
                        FROM Race_Results__r 
                        ORDER BY Racer__r.Age__c) 
            FROM Race__c 
            LIMIT 1
        ];

        Test.startTest();
        FormulaOneDAO dao = new FormulaOneDAO();
        Driver__c driver = dao.getYoungestDriverOnRace(race.Id, new List<String>{
            'Full_Name__c', 'Age__c'
        });
        Test.stopTest();

        System.assert(race.Race_Results__r.get(0).Racer__r.Id == driver.Id, 'Picked wrong yongest driver.');
    }

    @isTest
    static void getAllDriversByCircuitTest() {
        Race__c[] races = [SELECT Name FROM Race__c];

        Test.startTest();
        FormulaOneDAO dao = new FormulaOneDAO();
        Map<String, String[]> raceDriversMap = dao.getAllDriversByCircuit();
        Test.stopTest();

        System.assert(raceDriversMap.size() == races.size(), 'Wrong size of result map.');
        for (Race__c race: races) {
            System.assert(raceDriversMap.containsKey(race.Name), 'Map does not contain key - obligatory race name.');
        }
    }
}